x-application: &application
  image: e-petitions/ruby
  build: docker/ruby
  volumes:
    - .:/app
    - bundle:/bundle
    - cache:/cache
    - node_modules:/app/node_modules
  tmpfs:
    - /tmp/pids/
  depends_on:
    - postgres
    - mailcatcher

x-environment: &environment
  DATABASE_URL: "postgres://postgres:ZW4IvOPrXcbp2hyp@postgres:5432"
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
  SMTP_HOST: "mailcatcher"
  SMTP_PORT: "1025"
  SPROCKETS_CACHE: "/cache"
  PIDFILE: "/tmp/pids/server.pid"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ZW4IvOPrXcbp2hyp
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  mailcatcher:
    image: e-petitions/mailcatcher
    build: docker/mailcatcher
    expose:
      - "1025"
    ports:
      - "127.0.0.1:1080:1080"

  web:
    <<: *application
    environment:
      <<: *environment
    command: [
      "foreman", "start",
      "-f", "Procfile.dev"
    ]
    ports:
      - "127.0.0.1:3000:3000"
    stdin_open: true
    tty: true
    init: true

volumes:
  bundle:
  db:
  cache:
  node_modules:
