x-application: &application
  image: e-petitions/ruby
  build: docker/ruby
  volumes:
    - type: bind
      source: .
      target: /app
    - type: volume
      source: bundle
      target: /bundle
    - type: volume
      source: node_modules
      target: /app/node_modules
  tmpfs:
    - /tmp/pids/
  depends_on:
    - dnsmasq
    - postgres
    - mailcatcher
  dns:
    - 172.24.99.53

x-environment: &environment
  DATABASE_URL: "postgres://postgres:ZW4IvOPrXcbp2hyp@postgres:5432"
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
  OLLAMA_URL: "http://ollama:11434"
  PIDFILE: "/tmp/pids/server.pid"

services:
  dnsmasq:
    image: e-petitions/dnsmasq
    build: docker/dnsmasq
    volumes:
      - type: bind
        source: docker/dnsmasq/dnsmasq.conf
        target: /etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.24.99.53

  postgres:
    image: e-petitions/postgres
    build: docker/postgres
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ZW4IvOPrXcbp2hyp
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data

  mailcatcher:
    image: e-petitions/mailcatcher
    build: docker/mailcatcher
    expose:
      - "1025"
    ports:
      - "127.0.0.1:1080:1080"
    networks:
      default:
        ipv4_address: 172.24.99.30

  ollama:
    image: ollama/ollama
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - type: volume
        source: ollama
        target: /root/.ollama
    profiles:
      - ollama

  web:
    <<: *application
    environment:
      <<: *environment
    command: [
      "foreman", "start",
      "-f", "Procfile.dev"
    ]
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      default:
        ipv4_address: 172.24.99.31
    stdin_open: true
    tty: true
    init: true

  console:
    <<: *application
    environment:
      <<: *environment
    command: ["/bin/bash"]
    profiles:
      - console
    stdin_open: true
    tty: true
    dns:
      - 172.24.99.53

  e2e:
    <<: *application
    environment:
      <<: *environment
      DISABLE_FORCE_SSL: "true"
      RAILS_ENV: "production"
      RAILS_SERVE_STATIC_FILES: "true"
      SECRET_KEY_BASE: "6a5e319d068ceb629ce3cf4683b296a9"
      STORAGE_ADAPTER: "test"
      WEB_CONCURRENCY: "0"
      WEB_CONCURRENCY_MIN_THREADS: "5"
      WEB_CONCURRENCY_MAX_THREADS: "5"
    command: [
      "foreman", "start",
      "-f", "Procfile.dev"
    ]
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      default:
        ipv4_address: 172.24.99.31
    profiles:
      - e2e
    stdin_open: true
    tty: true
    init: true

networks:
  default:
    ipam:
      config:
        - subnet: 172.24.0.0/16
          ip_range: 172.24.99.0/24
          gateway: 172.24.99.254

volumes:
  bundle:
  db:
  node_modules:
  ollama:
