default: &default
  adapter: postgresql
  encoding: utf8
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres@localhost') %>
  pool: 5

development:
  <<: *default
  database: epets_development

test:
  <<: *default
  database: epets_test

production:
  <<: *default
  database: epets_production
  pool: <%= ENV.fetch('WEB_CONCURRENCY_MAX_THREADS') { 32 }.to_i %>
